# Generated by Django 5.0.4 on 2024-05-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_noticia_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodista',
            name='apellido',
        ),
        migrations.AlterField(
            model_name='periodista',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
